# Generated by Django 5.1.5 on 2025-02-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_brand_product_color_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='size',
        ),
    ]
