# Generated by Django 5.1.5 on 2025-03-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_product_stalk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=False, verbose_name='تخفیف خورده'),
        ),
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت تخفیف خورده'),
        ),
    ]
