# Generated by Django 5.1.5 on 2025-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_product_off_product_off_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف خورده'),
        ),
    ]
