# Generated by Django 5.1.5 on 2025-03-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_product_off_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.BooleanField(default=False, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان گارانتی'),
        ),
    ]
