# Generated by Django 5.1.5 on 2025-03-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_product_warranty_product_warranty_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prc_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف خورده'),
        ),
    ]
