# Generated by Django 5.1.5 on 2025-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_productcategoriesmain_productcategories_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoriesmain',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
