# Generated by Django 5.1.5 on 2025-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200, verbose_name='')),
                ('info_title', models.CharField(max_length=200, verbose_name='')),
                ('info_description', models.TextField(verbose_name='')),
                ('info_image', models.ImageField(upload_to='images/about_us', verbose_name='')),
                ('work_title', models.CharField(max_length=200, verbose_name='')),
                ('work_description', models.TextField(verbose_name='')),
                ('work_image', models.ImageField(upload_to='images/about_us', verbose_name='')),
                ('wholesale_sales_perc', models.FloatField(verbose_name='')),
                ('single_sales_perc', models.FloatField(verbose_name='')),
                ('installation_and_repairs_perc', models.FloatField(verbose_name='')),
                ('companies_image', models.ImageField(upload_to='images/about_us', verbose_name='')),
            ],
        ),
    ]
