# Generated by Django 5.1.5 on 2025-02-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0002_alter_aboutus_options_alter_aboutus_companies_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نمایندگی')),
                ('image', models.ImageField(upload_to='images/about_us')),
            ],
            options={
                'verbose_name': 'نمایندگی',
                'verbose_name_plural': 'نمایندگی ها',
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='companies_image',
        ),
    ]
