# Generated by Django 5.1.5 on 2025-02-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0003_companies_remove_aboutus_companies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='image',
            field=models.ImageField(upload_to='images/about_us', verbose_name='تصویر نمایندگی'),
        ),
    ]
