# Generated by Django 5.1.5 on 2025-02-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0004_alter_companies_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('mobile1', models.IntegerField(max_length=11, verbose_name='')),
                ('mobile2', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='')),
                ('mobile3', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('address', models.CharField(max_length=200, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
