# Generated by Django 5.1.5 on 2025-02-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس مغازه'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile1',
            field=models.IntegerField(verbose_name='شماره تماس اول'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile2',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تماس دوم'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile3',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تماس سوم'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی تلگرام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
