# Generated by Django 5.1.5 on 2025-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0006_alter_contactus_options_alter_contactus_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='home_description',
            field=models.TextField(default='', verbose_name='توضیحات صفحه خانه'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='تصویر صفحه خانه'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='home_title',
            field=models.CharField(default='', max_length=100, verbose_name='عنوان صفحه خانه'),
        ),
    ]
