# Generated by Django 5.1.5 on 2025-02-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0007_aboutus_home_description_aboutus_home_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
