# Generated by Django 5.1.5 on 2025-02-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0008_frequentlyquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=200, verbose_name='وظیفه شغلی')),
                ('image', models.ImageField(upload_to='images/team', verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
    ]
