# Generated by Django 5.1.5 on 2025-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0009_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/team', verbose_name='تصویر پروفایل'),
        ),
    ]
