# Generated by Django 5.1.5 on 2025-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0010_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='لوگو سایت'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='site_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام سایت'),
        ),
    ]
