# Generated by Django 5.1.5 on 2025-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0011_contactus_site_logo_contactus_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='post_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه پستی'),
        ),
    ]
