# Generated by Django 5.1.5 on 2025-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0012_contactus_post_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_price', models.IntegerField(verbose_name='هزینه پستی')),
                ('card_number', models.CharField(max_length=100, verbose_name='شماره کارت اول')),
                ('shaba_card_number', models.CharField(max_length=200, verbose_name='شماره شبا کارت اول')),
                ('owner_card_number', models.CharField(max_length=200, verbose_name='صاحب شماره کارت اول')),
                ('card_number2', models.CharField(max_length=100, verbose_name='شماره کارت دوم')),
                ('shaba_card_number2', models.CharField(max_length=200, verbose_name='شماره شبا کارت دوم')),
                ('owner_card_number2', models.CharField(max_length=200, verbose_name='صاحب شماره کارت دوم')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات بانکی',
            },
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='post_paid',
        ),
    ]
