# Generated by Django 5.1.5 on 2025-02-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0013_manyinfo_remove_contactus_post_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyinfo',
            name='post_price',
        ),
    ]
