# Generated by Django 5.1.5 on 2025-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0015_alter_manyinfo_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyinfo',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره کارت اول'),
        ),
        migrations.AlterField(
            model_name='manyinfo',
            name='card_number2',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره کارت دوم'),
        ),
    ]
