# Generated by Django 5.1.5 on 2025-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0016_alter_manyinfo_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyinfo',
            name='card_number',
            field=models.IntegerField(default=0, verbose_name='شماره کارت اول'),
        ),
        migrations.AlterField(
            model_name='manyinfo',
            name='owner_card_number2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='صاحب شماره کارت دوم'),
        ),
        migrations.AlterField(
            model_name='manyinfo',
            name='shaba_card_number2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره شبا کارت دوم'),
        ),
    ]
