# Generated by Django 5.1.5 on 2025-02-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0017_alter_manyinfo_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyinfo',
            name='card_number2',
        ),
        migrations.RemoveField(
            model_name='manyinfo',
            name='owner_card_number2',
        ),
        migrations.RemoveField(
            model_name='manyinfo',
            name='shaba_card_number2',
        ),
    ]
