# Generated by Django 5.1.5 on 2025-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0018_remove_manyinfo_card_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyinfo',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='لوگو سایت'),
        ),
    ]
