# Generated by Django 5.1.5 on 2025-03-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0019_manyinfo_site_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile1',
            field=models.CharField(max_length=100, verbose_name='شماره تماس اول'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس دوم'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس سوم'),
        ),
    ]
