# Generated by Django 5.1.5 on 2025-03-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0020_alter_contactus_mobile1_alter_contactus_mobile2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='home_service_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='تصویر خدمات صفحه خانه'),
        ),
    ]
