# Generated by Django 5.1.5 on 2025-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0021_aboutus_home_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyinfo',
            name='card_number',
            field=models.CharField(default='', max_length=200, verbose_name='شماره کارت اول'),
        ),
    ]
