# Generated by Django 5.1.5 on 2025-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_orderdetail_post_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='post_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='post_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه پستی'),
        ),
    ]
