# Generated by Django 5.1.5 on 2025-02-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_remove_orderdetail_post_paid_order_post_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post_paid',
        ),
    ]
