# Generated by Django 5.1.5 on 2025-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_remove_order_post_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه پستی'),
        ),
    ]
