# Generated by Django 5.1.5 on 2025-02-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_order_post_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='post_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه پستی'),
        ),
    ]
