# Generated by Django 5.1.5 on 2025-02-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_orderdetail_post_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='post_paid',
        ),
    ]
