# Generated by Django 5.1.5 on 2025-02-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us_module', '0013_manyinfo_remove_contactus_post_paid'),
        ('order_module', '0007_remove_orderdetail_post_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_us_module.manyinfo'),
        ),
    ]
