# Generated by Django 5.1.5 on 2025-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_postprice_alter_order_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='post_paid',
            field=models.IntegerField(blank=True, default=50000, null=True, verbose_name='هزینه پستی'),
        ),
        migrations.DeleteModel(
            name='PostPrice',
        ),
    ]
