# Generated by Django 5.1.5 on 2025-02-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('short_description', models.CharField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('main_image', models.ImageField(upload_to='images/service', verbose_name='تصویر اصلی')),
                ('title_1', models.CharField(max_length=100, verbose_name='عنوان اول')),
                ('title_2', models.CharField(max_length=100, verbose_name='عنوان دوم')),
                ('title_3', models.CharField(max_length=100, verbose_name='عنوان سوم')),
                ('title_4', models.CharField(max_length=100, verbose_name='عنوان چهارم')),
                ('description_1', models.TextField(verbose_name='توضیحات اول')),
                ('description_2', models.TextField(verbose_name='توضیحات دوم')),
                ('description_3', models.TextField(verbose_name='توضیحات سوم')),
                ('description_4', models.TextField(verbose_name='توضیحات چهارم')),
                ('image', models.ImageField(upload_to='images/service', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
