# Generated by Django 5.1.5 on 2025-02-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='عنوان در url'),
        ),
    ]
