# Generated by Django 5.1.5 on 2025-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_module', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='home_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/service', verbose_name='تصویر صفحه اصلی'),
        ),
    ]
