# Generated by Django 5.1.5 on 2025-02-10 07:20

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('main_title', models.CharField(max_length=200, verbose_name='عنوان اصلی')),
                ('shamsi_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ شمسی')),
                ('sub_title1', models.CharField(max_length=200, verbose_name='عنوان اول')),
                ('sub_title2', models.CharField(max_length=200, verbose_name='عنوان دوم')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description1', models.TextField(verbose_name='توضیحات 1')),
                ('description2', models.TextField(verbose_name='توضیحات 2')),
                ('description3', models.TextField(verbose_name='توضیحات 3')),
                ('description4', models.TextField(verbose_name='توضیحات 4')),
                ('main_image', models.ImageField(upload_to='images/articles', verbose_name='تصویر اصلی')),
                ('image1', models.ImageField(upload_to='images/articles', verbose_name='تصویر 1')),
                ('image2', models.ImageField(upload_to='images/articles', verbose_name='تصویر 2')),
                ('image3', models.ImageField(upload_to='images/articles', verbose_name='تصویر 3')),
                ('quote', models.TextField(verbose_name='نقل قول')),
                ('quote_from', models.CharField(max_length=100, verbose_name='گوینده نقل قول')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
